/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as battleshipSol from "./Battleship.sol";
export type { battleshipSol };
import type * as createVerifierSol from "./createVerifier.sol";
export type { createVerifierSol };
import type * as moveVerifierSol from "./moveVerifier.sol";
export type { moveVerifierSol };
