/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boardVerifierSol from "./boardVerifier.sol";
export type { boardVerifierSol };
import type * as createVerifierSol from "./createVerifier.sol";
export type { createVerifierSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as moveVerifierSol from "./moveVerifier.sol";
export type { moveVerifierSol };
export type { BunnyBattle } from "./BunnyBattle";
