/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICreateVerifier } from "./ICreateVerifier";
export type { IMoveVerifier } from "./IMoveVerifier";
